### ISSUE TITLE
Sugerencias de mejora

### ISSUE THREAD

**Issue by tergontor** [MiguelAngelLV/gas_station_spain#1]
Probablemente puede ser problema de la API pero por si acaso comento algún defecto que he podido encontrar.  
1- De las gasolineras que sigo hay una que no la encuentro en la integración.  El código que tengo puesto y que funciona es 

```yaml
- scan_interval: 1800
    resource: https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/EstacionesTerrestres/FiltroMunicipio/3782
    sensor:
      - name: "Gasol.95 Easyoil Pto Manzanal km 351"
        value_template: >-
          {% set station = value_json['ListaEESSPrecio'] | selectattr('IDEESS', 'match', '4937') | first %}
          {{ station['Precio Gasolina 95 E5'] | replace(",",".") }}
        unit_of_measurement: "€/L"

```
Lo he buscado en la provincia de León pero no encuentro el pueblo de Manzanal del Puerto. 

2- Había una gasolinera que por código daba los datos pero por la integración sacaba "desconocido". Y digo había, porque en la actualidad ya marca el precio correcto.
Se trataba de la gasolinera situada en Madrid, Cepsa, calle Monte Igueldo.

3- Esto es una sugerencia de mejora en el caso que se pueda.  Se trata de que automáticamente el nombre de la entidad fuera el que aparece en el listado de la gasolinera, así no hay lugar a confusión si añades diferentes gasolineras de la misma marca. Luego puedes cambiar el nombre de la entidad si así se desea.

Saludos y gracias.

**Comment by MiguelAngelLV** [comment]
1): La gasolinera que has puesto, la 4937, corresponde:

```yaml
        {
            "C.P.": "24369",
            "Dirección": "CARRETERA N - VI KM. 351",
            "Horario": "L-D: 24H",
            "Latitud": "42,599222",
            "Localidad": "MANZANAL DEL PUERTO",
            "Longitud (WGS84)": "-6,230444",
            "Margen": "I",
            "Municipio": "Villagatón",
            "Precio Biodiesel": "",
            "Precio Bioetanol": "",
            "Precio Gas Natural Comprimido": "",
            "Precio Gas Natural Licuado": "",
            "Precio Gases licuados del petróleo": "",
            "Precio Gasoleo A": "1,569",
            "Precio Gasoleo B": "",
            "Precio Gasoleo Premium": "1,569",
            "Precio Gasolina 95 E10": "",
            "Precio Gasolina 95 E5": "1,679",
            "Precio Gasolina 95 E5 Premium": "1,679",
            "Precio Gasolina 98 E10": "",
            "Precio Gasolina 98 E5": "",
            "Precio Hidrogeno": "",
            "Provincia": "LEÓN",
            "Remisión": "dm",
            "Rótulo": "EASYGAS",
            "Tipo Venta": "P",
            "% BioEtanol": "0,0",
            "% Éster metílico": "0,0",
            "IDEESS": "4937",
            "IDMunicipio": "3782",
            "IDProvincia": "24",
            "IDCCAA": "08"
        }
```
No debes buscar por localidad, sino por municipio, está en «Villagatón».


2) Seguramente en el momento de intentar hacer la consulta, pillaría el servicio caído, y como hace consultas cada varias horas, hasta que no ha vuelto a tocar consultar pues se ha quedado con el error.

3)  Entiendo que te refieres que, además del municipio y el rótulo, se añada también la dirección?

**Actualmente es así:** Gasolina 95 E , Easygas
**Entiendo que quieres así:**  Gasolina 95 E, Easygas Carretera N-Vi km351 

Si es eso, poder se puede, pero la mayoría de las direcciones suelen ser muy largas y tengo que ver los tamaños máximos admitidos.
